### PR TITLE
Add configuration property to force usage of emulator credentials.

### PR DESCRIPTION
**Pull request by jfbenckhuijsen**
@loicmathieu Something along these lines?

### CODE REVIEW

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks!

**Comment by loicmathieu** [comment]
There is a formatting issue, can you run the formater so I can merge it?

```
mvn -f firestore/runtime net.revelc.code.formatter:formatter-maven-plugin:2.23.0:format
```

**Comment by jfbenckhuijsen** [comment]
Formatting should be fixed now

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks

**Pull request merged**
