### PR TITLE
feature(devservices): added bigtable dev service

### PR DESCRIPTION
**Pull request by zZHorizonZz**
This PR adds devservice for bigtable. Similar to firstore or pubsub emulators.

### CODE REVIEW

**Comment by zZHorizonZz** [comment]
I'm now wondering Is there a reason why there isn't a Bigtable/admin client producer?

**Review by loicmathieu — APPROVED** [review]
LGTM, thanks a lot

**Comment by loicmathieu** [comment]
> I'm now wondering, Is there a reason why there isn't a Bigtable/admin client producer?

At the time being, it was because there is not a single client but multiple ones.
I think adding a producer for the client would be a good addition.

**Comment by zZHorizonZz** [comment]
> At the time being, it was because there is not a single client but multiple ones. I think adding a producer for the client would be a good addition.

OK then I will try to look into it and with it, I will also add the documentation for this devservice.

**Pull request merged**
