### PR TITLE
Quarkus 2.0

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by loicmathieu** [comment]
This PR is failing due to `java.lang.ClassNotFoundException: com.aayushatharva.brotli4j.decoder.DecoderJNI$Wrapper` while building the native image.

So it is blocked untill https://github.com/quarkusio/quarkus/pull/17604 is backported to 2.0 and a release is done.

**Comment by gsmet** [comment]
I will release a CR3 tomorrow if all goes well.

**Comment by loicmathieu** [comment]
Thanks @gsmet with 2.0.0.CR3 all green ;)

@ppalaga you can use the version from main to try with Camel, I didn't publish CR nor snapshot versions yet, maybe this needs to be done someday to easy the integration between us.

**Comment by ppalaga** [comment]
Yes, testing with s snapshot locally now. A CR release would be handy to be able to test also within Quarkus Platform and within Camel K (depends on Camel Quarkus)

**Comment by ppalaga** [comment]
Our tests passed with your snapshot.

**Pull request merged**
