### PR TITLE
Delete unecessary ; in pubsub documentation

### PR DESCRIPTION
**Pull request by lemoigne-yt**

### CODE REVIEW

**Comment by loicmathieu** [comment]
@all-contributors add @lemoigne-yt for documentation

**Comment by loicmathieu** [comment]
Thanks @lemoigne-yt nice spot ;)

**Comment by yatho** [comment]
Thank you :).

**Comment by loicmathieu** [comment]
@yatho if you prefere to re-submit it with you personal account please do it. I'll close this one.

**Comment by loicmathieu** [comment]
Superseded by #249

**Pull request closed without merging**
