### PR TITLE
Upgrade to Quarkus 2.0.0.CR2

### PR DESCRIPTION
**Pull request by ppalaga**
An upgrade to Quarkus 2.0.0.CR2 to see whether https://github.com/apache/camel-quarkus/issues/2692 can be reproduced on your CI

### CODE REVIEW

**Comment by ppalaga** [comment]
Ups no CI here... 
@loicmathieu could you please have a look if you can reproduce https://github.com/apache/camel-quarkus/issues/2692 with your tests?

**Comment by loicmathieu** [comment]
@ppalaga I already have a branch with 2.0 in it, I didn't merge it yet as 2.0 is a long running update and I would keep the possibility to still release main.

Can you open an issue with a link to https://github.com/apache/camel-quarkus/issues/2692 ? Normally native image are build in the CI but I don't remember if I already run it for my 2.0 branch.

I plan to make a last release on the current main branch this week so I can move to Quarkus 2.0 soon.

**Comment by ppalaga** [comment]
Thanks for the info, @loicmathieu ! Could you please share your branch in some way, e.g. as a draft pull request so that we can try it in Camel Quarkus and give feedback?

Opened https://github.com/quarkiverse/quarkus-google-cloud-services/issues/119

**Comment by loicmathieu** [comment]
https://github.com/quarkiverse/quarkus-google-cloud-services/pull/120

It's still based on Alpha version.
I'll update it to CR2 soon, now that I merged your first PR if you openned a PR on this repo the CI would run now (this seems to be a new functionality on Github, PRs from newcommer didn't run the CI).

**Comment by loicmathieu** [comment]
My PR is now based on CR2 and failing on the CI due to the native image issue with Brotli decoder, as long as no Quarkus 2 release will be done with the fix this will not work.

I'm closing this one, you can track #120 for more info

**Pull request closed without merging**
