### PR TITLE
feature(bigtable): added bigtable client creation

### PR DESCRIPTION
**Pull request by zZHorizonZz**
This PR introduces an experimental version of the Bigtable client creation. 

**Summary:**

- Introduced a BigtableClient annotation that qualifies an injected Bigtable client.
- The BigtableClientProcessor class is responsible for registering beans, discovering injected beans, generating bigtable client producers, and transforming injection points. This ensures the right Bigtable client is used based on the configuration and qualifiers.
- The main class BigtableClients handles the creation of the Bigtable client.
- The system for bean creation is based on grpc client bean creation.

Also configuration will be made so that you can configure it like this:

```
quarkus.google.cloud.bigtable.clients.test-client.instance-id=test-instance
```

or default client:

```
quarkus.google.cloud.bigtable.clients.instance-id=test-instance
```

The introduced Bigtable client creation is experimental and may be subject to changes based on further testing.

### CODE REVIEW

**Comment by zZHorizonZz** [comment]
@loicmathieu When you have a bit of time, could you take a look at this? If the system this PR introduces is okay, can I potentially move forward or should I rework it?

**Review by loicmathieu — COMMENTED** [review]
Hi,
Thanks for the contribution.
Is there a strong need for multiple client support? It complexifies a lot the PR where a simple approach with a CDI producer would have worked if only one instance is published.

**Comment by zZHorizonZz** [comment]
> Is there a strong need for multiple client support? It complexifies a lot the PR where a simple approach with a CDI producer would have worked if only one instance is published.

So, yeah, that's why I wanted to wait first since you mentioned in https://github.com/quarkiverse/quarkus-google-cloud-services/pull/504#issuecomment-1723174438 something about multiple clients, etc. Also, I'm not sure if it's normal to use multiple Bigtable instances or just one in production. In any case, I will close this PR and create a new one with just a simple producer. 👍

**Comment by loicmathieu** [comment]
Yes, thanks, this would be easier to maintant!

**Pull request closed without merging**
