### PR TITLE
Fix a11y-base version to avoid dependency convergence issue

### PR DESCRIPTION
**Pull request by loicmathieu**

### CODE REVIEW

**Comment by gsmet** [comment]
You shouldn't need to do this at your level I think.

@phillip-kruger told me it was fixed in recent version and for latest 3.3, I think I ended up adding the dependency in the BOM.

With which version do you have this issue?

**Comment by loicmathieu** [comment]
There were ecosystem CI failures.

There is other issues with 3.4 that I need to sort out, I'll remove the dependency convergence when doing the 3.4 migration.

**Comment by gsmet** [comment]
I wouldn't expect problems with `main` as @phillip-kruger told me this was fixed. @phillip-kruger can you confirm?

**Comment by phillip-kruger** [comment]
Yes main should be fixed

**Comment by loicmathieu** [comment]
I removed it and upgrade to Quarkus 3.4.0.CR1, everything works.

**Pull request merged**
